### ISSUE TITLE
twentysixteen missing from 4.4 versions

### ISSUE THREAD

**Issue by egifford** [johnpbloch/wordpress#19]
This project is really useful. Thanks so much for maintaining it!

Is it possible to have the twentysixteen theme included in the next release?

**Comment by johnpbloch** [comment]
I'll look into that. In the meantime, you can get it using [wpackagist](http://wpackagist.org) by requiring `wpackagist-theme/twentysixteen` in your own composer.json.

**Comment by johnpbloch** [comment]
How odd. The subversion repositories only have ten through fifteen, although the release zip from .org has only fourteen through sixteen.

I'm not entirely convinced that the core package should be shipping with sub-packages, since that's technically a hidden dependency. Ideally, sites that use composer to manage their installation should also add explicit dependencies on all themes they expect to be present.

Obviously, for backwards compatibility, the themes won't be leaving this repository, I'm just not sure I'll continue to add themes if they don't come from the core repository.

**Comment by johnpbloch** [comment]
It would appear twentysixteen is not added to the core svn repository as an external either. (at least not the one my script uses).

**Comment by egifford** [comment]
Thanks for following up on this so quickly and for the tip on installing `wpackagist-theme/twentysixteen`.

I had noticed the discrepancy with the release zip.  But I didn't dig as deep as you did.  I hadn't realized that twentysixteen hadn't been added to svn repo.  That clearly explains why it isn't appearing in this project.

I think the only 'gotcha' for this project is that a clean WordPress install activates the newest 'core' theme, in this case twentysixteen.  That is how I noticed it was missing.

Adding `wpackagist-theme/twentysixteen` as a dependency of this project could be a way to ensure it is present, but it also doesn't feel quite right.  I'm not sure how that would interact with `composer/installers`.

Anyway, my curiosity is satisfied for this issue.  Unless you want to make a change, we can close this issue.

Thanks again. :)

**Comment by AppSynergy** [comment]
https://core.trac.wordpress.org/ticket/34306

> "...Twenty Sixteen will not be merged to SVN, but should be a default theme for new installs"

So they've decided to ship 6 themes that are **not** the default, but exclude the one that is.

Yeah.
