### ISSUE TITLE
TAG 5.1 is not yet there?

### ISSUE THREAD

**Issue by 7php** [johnpbloch/wordpress#39]
Hi,
been more than 24hrs since wordpress v5.1 is LIVE.. but there is not 5.1 tag yet?
/c @johnpbloch

**Comment by SeBsZ** [comment]
Yeah, I mentioned it in this closed issue here: https://github.com/johnpbloch/wordpress/issues/37 because the same thing happened with 5.0. Though it might be better to create a new issue. thanks!
I'm sure this will be fixed very quickly.

**Comment by johnpbloch** [comment]
This is related to https://github.com/johnpbloch/wordpress-core/issues/19

In an effort to keep the problem from getting worse, I temporarily turned off the bot. It'll be back online this morning and 5.1 will get picked up then. Sorry for any inconvenience!

**Comment by 7php** [comment]
Ok @johnpbloch , thank you for the response. It's OK, things happen, thankful that you are addressing it.
And thank you for all you do with johnpbloch/wordpres

cheers

**Comment by hackles** [comment]
fwiw [`roots/wordpress`](/roots/wordpress) is a drop-in replacement and has 5.1 ¯\\_(ツ)\_/¯

**Comment by johnpbloch** [comment]
@hackles true story. When I saw what @austinpray did to make `roots/wordpress` I was kicking myself for a week for not having thought of such an elegant solution.

5.1 has been built and tagged in this repo as well now.

**Comment by austinpray** [comment]
@johnpbloch Thanks man! Yeah I was pretty happy with what I ended up with. Definitely feel free to use as much of the code/concepts as you want if you think it is useful. We were trying to avoid cross-promoting our package in this repo. Piggybacking on bug reports seems in poor taste. But it seems @hackles knew that since he made a throwaway haha.
