### ISSUE TITLE
4.1.1 Packagist Tag not working?

### ISSUE THREAD

**Issue by blueliquiddesigns** [johnpbloch/wordpress#4]
Hi,

I'm using composer and saw the 4.1.1 update was released so I changed `"johnpbloch/wordpress": "4.1.0",` to `"johnpbloch/wordpress": "4.1.1",` however after I run `composer update` and log into the website is still says I'm running 4.1 and need to update. 

Am I missing something?

**Comment by blueliquiddesigns** [comment]
Nevermind. It appears to have resolved itself.

**Comment by johnpbloch** [comment]
Thanks for reporting this, @blueliquiddesigns.

For future reference (for all our future selves), the script I use to keep the repo up-to-date with upstream runs every 15 minutes and the SVN repo it tracks (http://core.svn.wordpress.org) often takes several hours to update its tags. Between those two, I usually wait at least 12 hours before trying to bump a tag, but YMMV. If those updates are more critical to anybody, perhaps using the development branch for a version tree (e.g. `4.1.*@dev`) is a preferable solution, since it doesn't rely on the core team tagging a new release (maintenance fixes are often committed directly to the branch in the SVN repo).

**Comment by blueliquiddesigns** [comment]
Thanks for the feedback.
