### ISSUE TITLE
How quickly does the automated update of this occur?

### ISSUE THREAD

**Issue by conatus** [johnpbloch/wordpress#7]
Thanks for this great resource.

Automatic just pushed [a security update](https://wordpress.org/news/2015/04/wordpress-4-2-1/), how quickly before I can grab it from Composer?

**Comment by conatus** [comment]
It already happened, my bad. Hmmmm.

**Comment by johnpbloch** [comment]
For what it's worth, there are 2 things at play in getting a new release out:

This repository tracks the svn repo at http://core.svn.wordpress.org/. That repo gets updated upstream by the core team, but tags don't get synced immediately. Sometimes it takes them an hour or two to sync tags. On top of that, my update script runs on a 15 minute cron schedule, so that could add up to 15 minutes of delay even after the tags have been synced.

I have plans to rewrite the update script to use http://develop.svn.wordpress.org to tag releases with only a 15 minute maximum delay and also to alias the master branch to the next release dev branch as discussed in #6.

**Comment by johnpbloch** [comment]
For now, if point releases are important enough to get more quickly than the tagged release lag permits, I'd advise using the dev branch for that major version (e.g. `4.2.x-dev`).
